build: unbreak compilation with clang libc++
unary_function is obsolete with C++11 and removed in C++17.
gnu-gcc-libstdc++ still has the class, but llvm-clang-libc++ does
not, and there is a compile error.

vmime should have just stopped using unary_function with commit
v0.9.2-48-g8564b2f8.

	$ cat x.cpp
	$ clang++ -std=c++17 -stdlib=libc++ -c x.cpp
	In file included from x.cpp:1:
	In file included from /usr/local/include/vmime/net/transport.hpp:34:
	In file included from /usr/local/include/vmime/net/service.hpp:36:
	In file included from /usr/local/include/vmime/net/session.hpp:40:
	In file included from /usr/local/include/vmime/utility/url.hpp:30:
	/usr/local/include/vmime/propertySet.hpp:339:33: error: no template named
	/'unary_function' in namespace 'std'; did you mean '__unary_function'?
		class propFinder : public std::unary_function <shared_ptr <property>, bool> {
					  ~~~~~^~~~~~~~~~~~~~
					       __unary_function