build: set _POSIX_C_SOURCE
Cygwin uses the Newlib C library. The vmime build procedure selects a
strict ISO standard (-std=c++11), in which the availability of POSIX
interfaces is not guaranteed. Possible options are either
`-std=gnu++11` or `_POSIX_C_SOURCE`.

```
~/src/vmime/platforms/posix/posixChildProcess.cpp: In constructor "vmime::platforms::posix::posixChildProcess::posixChildProcess(const vmime::utility::file::path&)":
~/src/vmime/platforms/posix/posixChildProcess.cpp:224:9: error: "sigemptyset" was not declared in this scope
    sigemptyset(&m_oldProcMask);
~/src/vmime/platforms/posix/posixHandler.cpp: In member function "virtual const vmime::string vmime::platforms::posix::posixHandler::getHostName() const":
~/src/vmime/platforms/posix/posixHandler.cpp:170:11: error: "::gethostname" has not been declared; did you mean "getHostName"?
    ::gethostname(hostname, sizeof(hostname));
~/src/vmime/platforms/posix/posixHandler.cpp:174:25: error: aggregate "addrinfo hints" has incomplete type and cannot be defined
    struct addrinfo hints;
```

Setting `_POSIX_C_SOURCE` has a side-effect: it can disable the
toolchain's default selection, e.g. disable an implicit
`-D_BSD_SOURCE`, which in turn causes getthrid()/gethostname() to be
no longer imported. Set `_BSD_SOURCE` in the necessary spots too.